name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        duckdb-version:
          - '1.0.0'
          - '1.1.0'
          - '1.1.1'
        raku-version:
          - '2024.08'
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: zef install --deps-only .
      - name: Install native deps
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v${{ matrix.duckdb-version }}/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip
          sudo cp libduckdb.so /usr/lib
      - name: Run Tests
        run: raku ./make -v test
